name: flutter_ytlog
description: "Log Util for Flutter"
version: 0.0.3
homepage: https://github.com/and2long/flutter_ytlog

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^6.0.0

flutter:
